name: Publish
run-name: ${{ github.ref_name }}-${{ github.actor }}

on:
  push:
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Java CI
        uses: NikitaLafinskiy/habit-tracker-iac/.github/actions/java-ci@main
        with:
          java-version: '24'

      - name: Publish to GitHub Packages
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish --no-daemon
